# Generated by Django 2.1.4 on 2018-12-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ascensor',
            fields=[
                ('id_ascensor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_termino', models.DateTimeField()),
                ('num_fallas', models.IntegerField()),
                ('num_reparaciones', models.IntegerField()),
                ('num_repuestos', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantencion.Cliente', unique=True)),
                ('id_ascensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantencion.Ascensor', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('correo', models.EmailField(max_length=60)),
                ('contraseña', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantencion.Tecnico', unique=True),
        ),
    ]
