# Generated by Django 2.1.4 on 2018-12-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='orden',
            name='hora_inicio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orden',
            name='hora_termino',
            field=models.CharField(max_length=50),
        ),
    ]
