# Generated by Django 2.1.4 on 2018-12-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mantencion', '0004_auto_20181212_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asignacion_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantencion.Cliente')),
                ('tecnico', models.ManyToManyField(to='Mantencion.Tecnico')),
            ],
        ),
    ]
