# Generated by Django 2.1.4 on 2018-12-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mantencion', '0005_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='folio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Mantencion.Asignacion'),
        ),
    ]
